### ISSUE TITLE
Allow the user to subscribe to our newsletters

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#12]
Include E-mail Id box in footer so that a user can subscribe to our newsletters by providing their mail id's .

Please check out the following screenshot for a better understanding : 
![mock-up](https://user-images.githubusercontent.com/30520066/29805827-a0738998-8ca9-11e7-8e71-43ca1f979523.png)

**Comment by dgteqp** [comment]
When they click on subscribe newsletter button, need to fill name, phone number & email id.
Those details are sending to our mail id i.e info@digitalequipmentsindia.com 
working in my local system.

**Comment by dgteqp** [comment]
Fixed issue
