### ISSUE TITLE
Add RESET-FILTER button in Browse pages

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#20]
Add Reset-Filter button in the browse pages .
Discuss further.

**Comment by dgteqp** [comment]
Upon clicking the Reset button, All filters should be cleared.
Product Type (with HIRE, SALE, HIRE&SALE options) should also be cleared. This may need an enhancement of an additional option of "SELECT TYPE"

**Comment by dgteqp** [comment]
Resolved except select type
