### ISSUE TITLE
Replace DIGITAL EQUIPMENTS INDIA with  BIG EQUIPMENTS INDIA

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#23]
Change the "DIGITAL EQUIPMENTS INDIA" text everywhere around the page to "BIG EQUIPMENTS INDIA"

For example : 
1.About Us page
2. How it works page

**Comment by dgteqp** [comment]
Resolved

**Comment by degeqp** [comment]
Also fix this in the below listed pages:
3.Terms of use
4.Privacy policy

**Comment by dgteqp** [comment]
Change all references including From/To Email addresses or any other links to the domain and website

**Comment by dgteqp** [comment]
Changed as per the requirement. bbt right mails are sending from info@digitalequipmentsindia.com,
Once we get control. we can change info@bigequipmentsindia.com, 
Will reopen this bug in future.
