### ISSUE TITLE
Visitor Count need to be captured

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#29]

**Comment by dgteqp** [comment]
Resolved
Created new table core_visitors in bei_beta database. 
When user browse our site, I am capturing ip address, date, country & city.
Now we can get number of visitors from data base.
we will work in future in CP for view number of visited in days

**Comment by dgteqp** [comment]
capture lat, long, and city

**Comment by dgteqp** [comment]
At this time, we have added core_visitors table
