### ISSUE TITLE
19-09-17 | Update our Homepage Classifieds with given data

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#48]
Dear Team,

 Kindly update our Homepage Classifieds with the following data

Classified-2 & 6: WANTED IN PARADEEP: 60-80 TON TRUCK MOUNTED TELESCOPIC  CRANE WITH 120 FT. BOOM FOR 1 YEAR at IOCL PROJECT

**Comment by dgteqp** [comment]
Resolved
