### ISSUE TITLE
20-09-17 | Update yesterday's classifieds with given data

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#49]
Dear Team,

 Kindly update yesterday's classifieds with the following

Classified 2: WANTED IN GUJARAT: HYDRAULIC TRUCK CRANE WITH 25-30 TON FOR 2 MONTHS 

Classified 6: WANTED IN GUJARAT: HYDRAULIC TRUCK CRANE WITH 40 TON FOR 2 MONTHS

**Comment by dgteqp** [comment]
Resolved
