### ISSUE TITLE
Remove "KOCHI METRO" ad from 7 scrolls in homepage 1,3,4

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#51]
Replace 1st scroll message with : 1. THE LOGISTICS REVOLUTION...
Pioneering an innovative and easier way to facilitate equipments related logistics, across India

3rd scroll message : 3. GROW YOUR BUSINESS WITH US
Contact us for placing your classifieds with us
<Make "Contact us" as a clickable tag for info@digitalequipmentsindia.com>

4th scroll message : 4. DEI: INFRASTRUCTURE REVOLUTION OF INDIA
Digital India driven initiative, aiming to bring all construction related equipments in India to a single platform.

**Comment by dgteqp** [comment]
Resolved
