### ISSUE TITLE
New Scroll Messages

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#52]
Message 1: 
New URGENT Requirement for Purchase : 40T , 100T, 200T, 350T Cranes
(Contact Message)

Message 3: 
New URGENT Requirement for Purchase : 40Ton ALL-TERRAIN Crane
(Contact Message)

Message 4: 
New URGENT Requirement for Purchase : 100Ton ALL-TERRAIN Crane
(Contact Message)

Message 5: 
New URGENT Requirement for Purchase : 200Ton ALL-TERRAIN Crane
(Contact Message)

Message 7: 
New URGENT Requirement for Purchase : 350Ton ALL-TERRAIN Crane
(Contact Message)

**Comment by dgteqp** [comment]
Resolved
