### ISSUE TITLE
New USER INTERFACE (UI) as recommended by Dharma Sir 

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#57]
New suggestions for UI : 
1. Remove the pop-up on home page, on clicking the Equipments and display buttons.
2. Replace 4 Options (HIRE, SUPPLY, SELL, BUY) with 3 following Options (HIRE, SUPPLY, BUY).
3. Provided 3 buttons (HIRE, SUPPLY, BUY) must be clickable and lead to respective pages.
4. Implement hover color to the buttons

**Comment by dgteqp** [comment]
Resloved
