### ISSUE TITLE
Update classifieds in Home-Page

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#65]
On request of Goutham, Kindly update our Home page classifieds with the following:

Replace the following with 1,2,3,4 scrolls

1. Urgent Requirement at Guwahati, Assam: 400 Ton All Terrian Crane
2. Urgent Requirement at Andhra Pradesh & Telangana: 120 Tons All Terrian Crane
3. Need 450 Tons Crawler Crane at Sangli, Maharashtra.
4. Urgent Requirement at Nellore, Andhra Pradesh: 70 Tons Crawler for APGENCO project.

Replace 5,6,7 with our own original Scrolls.

5. FIND YOUR CUSTOMERS EASILY 
Contact us for placing your classifieds with us
<Make "Contact us" as a clickable tag for info@bigequipmentsindia.com>

6. HELP IS ONE-CLICK AWAY, 24X7
Contact us for placing your classifieds with us
<Make "Contact us" as a clickable tag for info@bigequipmentsindia.com>

7. INTERNATIONAL SUPPLIERS FOR INDIAN CUSTOMERS
Contact us for placing your classifieds with us
<Make "Contact us" as a clickable tag for info@bigequipmentsindia.com>

**Comment by dgteqp** [comment]
Resolved
