### ISSUE TITLE
Change the Equipments from "sell" to "hire"

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#71]
On goutham's request
Kindly find the below codes of equipments. These equipments were uploaded in "SELL". Kindly shift these equipments to "HIRE" in their respective categories.
CAT0250S0016C Cranes
CAT0250S0016B Cranes
CAT0350S0016A Cranes
CAT0350S00169 Cranes
CAT0500S00168 Cranes
CCR0300S00167 Cranes
CAT0500S00166 Cranes
CAT0700S00165 Cranes
CCR0300S00164 Cranes
CHT0060S00163  Cranes
CHT0062S00162 Cranes
DCO0007S00161 Dumpers
DCO0007S00160 Dumpers
DCO0007S0015F Dumpers
DCO0016S0015D Dumpers

Kindly change these equipments from "SELL" to "HIRE"

**Comment by dgteqp** [comment]
resolved
