### ISSUE TITLE
Manage the 7 scrolls in Homepage

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEI-Internal#8]
The scrolling messages in the homepage should be manageable.

DEI (Data Operator) should be able to change the text of the scrolling messages.

**Comment by dgteqp** [comment]
Our IT team have to work on new design.

**Comment by dgteqp** [comment]
Design a new table for messages.
It is an enhancement

**Comment by dgteqp** [comment]
Check and close this issue
